export const CACHE_KEY = "exam_prep_tracker_cache";

export const TRACKING_FIELDS = [
  { key: "lecture", label: "Lecture" },
  { key: "notes", label: "Notes" },
  { key: "revision", label: "Revision" }
];

export const DOM_IDS = {
  appTitleText: "appTitleText",
  customExamCategory: "customExamCategory",
  customExamForm: "customExamForm",
  customExamMessage: "customExamMessage",
  customExamName: "customExamName",
  customTopicForm: "customTopicForm",
  customTopicMessage: "customTopicMessage",
  customTopicName: "customTopicName",
  customTopicSection: "customTopicSection",
  customTopicSubject: "customTopicSubject",
  diaryContainer: "diaryContainer",
  diaryForm: "diaryForm",
  diaryMood: "diaryMood",
  diaryText: "diaryText",
  examCardsContainer: "examCardsContainer",
  examHome: "examHome",
  mockContainer: "mockContainer",
  mockForm: "mockForm",
  mockName: "mockName",
  mockScore: "mockScore",
  mockTotal: "mockTotal",
  mockDate: "mockDate",
  mockNotes: "mockNotes",
  prepNav: "prepNav",
  pyqContainer: "pyqContainer",
  pyqForm: "pyqForm",
  pyqName: "pyqName",
  pyqYear: "pyqYear",
  pyqScore: "pyqScore",
  pyqNotes: "pyqNotes",
  trackerHeader: "trackerHeader",
  trackerSubtitle: "trackerSubtitle",
  trackerTitle: "trackerTitle",
  trackerView: "trackerView",
  changeExamBtn: "changeExamBtn",
  contentContainer: "contentContainer",
  lectureDone: "lectureDone",
  notesDone: "notesDone",
  revisionDone: "revisionDone",
  loginBtn: "loginBtn",
  logoutBtn: "logoutBtn",
  mainProgressBar: "mainProgressBar",
  mockDone: "mockDone",
  overallProgress: "overallProgress",
  progressChart: "progressChart",
  pyqAttemptsDone: "pyqAttemptsDone",
  searchInput: "searchInput",
  subjectProgressContainer: "subjectProgressContainer",
  tabsContainer: "tabsContainer",
  totalTopics: "totalTopics"
};
